// Dados das duas trilhas Go — gerados a partir dos ficheiros markdown originais.
const TRILHA_PRINCIPAL = {
  id: "principal",
  titulo: "100 exercícios até à primeira API",
  intro: "Guia progressivo em 13 blocos, dos fundamentos da linguagem ao deploy de uma API REST completa.",
  blocos: [
    {
      id: "b0",
      titulo: "Bloco 0 — Fundamentos da linguagem",
      faixa: "Ex 0.1–0.15",
      descricao: "Tudo o que precisas de saber antes de structs. Se já dominas isto (variáveis, tipos, funções, loops, ponteiros básicos), passa direto ao Bloco 1. Mesmo assim vale a pena confirmares cada ponto, porque Go tem convenções próprias que diferem de outras linguagens.",
      recursos: [
        { label: "Tour of Go — Basics", url: "https://go.dev/tour/basics/1" },
        { label: "Go by Example — Basics", url: "https://gobyexample.com/" },
        { label: "Effective Go — Formatting", url: "https://go.dev/doc/effective_go#formatting" },
        { label: "How to Install Go", url: "https://go.dev/doc/install" },
      ],
      exercicios: [
        "Instala o Go, ou confirma a versão instalada com go version, e cria o teu primeiro go.mod com go mod init.",
        "Escreve um \"Hello, World\" e corre com go run. Depois compila com go build e corre o binário gerado, e repara na diferença entre os dois fluxos.",
        "Declara variáveis das 3 formas possíveis em Go: var x int = 5, var y = 5 com inferência de tipo, e z := 5 como short declaration. Explica por escrito quando usarias cada uma.",
        "Cria uma variável de cada tipo básico: int, float64, string, bool, rune e byte. Imprime o tipo de cada uma com %T no Printf.",
        "Cria constantes com const, incluindo um bloco const ( ... ) que usa iota para gerar uma sequência, por exemplo os dias da semana.",
        "Usa operadores aritméticos, de comparação e lógicos (+ - * / %, == != < > && ||), escrevendo exemplos que mostrem a diferença entre a divisão inteira de 7 / 2 e a divisão com float64.",
        "Usa if/else e a forma de if com inicialização, como if n := calcular(); n > 0 { ... }. Este padrão aparece constantemente em Go: já o usaste sem saberes em _, err := fmt.Scan(&n); if err == nil.",
        "Usa switch sem expressão, equivalente a uma cadeia de if/else if, e switch com um valor.",
        "Pratica os 3 formatos de for em Go, já que a linguagem não tem while nem do-while: for i := 0; i < 10; i++, for com apenas uma condição, e for infinito interrompido com break.",
        "Implementa a função dividir(a, b int) (int, int), com múltiplos valores de retorno, que devolve o quociente e o resto.",
        "Reescreve a função anterior como dividir(a, b int) (q, r int), usando named return values, e devolve o resultado só com return, sem argumentos.",
        "Implementa a função variádica soma(numeros ...int) int.",
        "Pratica ponteiros, a base que vais precisar para pointer receivers no Bloco 1: cria uma variável, imprime o seu endereço com &, cria um ponteiro para ela, altera o valor através do ponteiro com *, e confirma que a variável original mudou.",
        "Escreve a função Dobrar(n *int), que recebe um ponteiro e duplica o valor original, e compara com uma versão DobrarValor(n int) int, que devolve o dobro sem alterar o original. É o mesmo princípio que vais aplicar a Concluir() no Bloco 1.",
        "Corre gofmt -l . no teu projeto para listares os ficheiros mal formatados, e depois gofmt -w . para os corrigires automaticamente. Ao contrário da maioria das linguagens, Go tem uma única formatação oficial, e vale a pena adotares isto desde já.",
      ],
    },
    {
      id: "b1",
      titulo: "Bloco 1 — Structs & Methods",
      faixa: "Ex 1–10",
      descricao: "Structs agrupam campos relacionados; methods ligam funções a um tipo via receiver (valor ou ponteiro).",
      recursos: [
        { label: "Tour of Go — Structs", url: "https://go.dev/tour/moretypes/2" },
        { label: "Tour of Go — Methods", url: "https://go.dev/tour/methods/1" },
        { label: "Go by Example — Structs", url: "https://gobyexample.com/structs" },
        { label: "Go by Example — Methods", url: "https://gobyexample.com/methods" },
        { label: "Effective Go — Pointers vs Values", url: "https://go.dev/doc/effective_go#pointers_vs_values" },
      ],
      exercicios: [
        "Cria o struct Task com os campos ID int, Titulo string e Concluida bool.",
        "Implementa o método (t Task) Resumo() string, que devolve \"[✓] Titulo\" quando Concluida é true, ou \"[ ] Titulo\" caso contrário.",
        "Implementa o método (t *Task) Concluir(), com pointer receiver, que muda Concluida para true. Depois escreve a mesma função com value receiver, chama as duas no main e compara o resultado antes e depois de cada chamada.",
        "Cria o struct Produto com os campos Nome string, Preco float64 e Stock int.",
        "Implementa o método (p Produto) EmStock() bool, que devolve true quando Stock é maior que 0.",
        "Implementa o método (p *Produto) Vender(qtd int) error, que reduz o Stock e devolve um erro quando não há stock suficiente.",
        "Cria os structs Retangulo, com os campos Largura e Altura float64, e Circulo, com o campo Raio float64. Dá a cada um o seu próprio método Area().",
        "Cria o struct Endereco com os campos Cidade e Pais string, e usa-o dentro do struct Cliente como um campo aninhado chamado Endereco.",
        "Cria o struct ClienteVIP embutindo Cliente e adicionando o campo Desconto float64. Confirma que consegues aceder a vip.Nome diretamente, sem escreveres vip.Cliente.Nome, porque Go promove os campos do struct embutido.",
        "Implementa o método (t Task) String() string, que satisfaz a interface fmt.Stringer. Depois chama fmt.Println(t1) diretamente e repara que Go usa esse método automaticamente.",
      ],
    },
    {
      id: "b2",
      titulo: "Bloco 2 — Slices, Arrays & Maps",
      faixa: "Ex 11–25",
      descricao: "Slices são a estrutura de dados mais usada em Go; arrays têm tamanho fixo; maps são pares chave-valor.",
      recursos: [
        { label: "Tour of Go — Slices", url: "https://go.dev/tour/moretypes/7" },
        { label: "Tour of Go — Maps", url: "https://go.dev/tour/moretypes/19" },
        { label: "Go by Example — Slices", url: "https://gobyexample.com/slices" },
        { label: "Go by Example — Arrays", url: "https://gobyexample.com/arrays" },
        { label: "Go by Example — Maps", url: "https://gobyexample.com/maps" },
        { label: "Go Slices: usage and internals", url: "https://go.dev/blog/slices-intro" },
      ],
      exercicios: [
        "Cria um slice []Task com 4 tarefas e imprime o Resumo() de cada uma usando range.",
        "Implementa TarefasPendentes(tarefas []Task) []Task, que filtra as tarefas com Concluida igual a false, construindo o resultado com append.",
        "Implementa TarefasConcluidas(tarefas []Task) []Task, que faz o inverso da função anterior.",
        "Implementa ContarConcluidas(tarefas []Task) int, que conta as tarefas concluídas sem criar um novo slice.",
        "Implementa TituloMaisLongo(tarefas []Task) string, que percorre o slice e guarda o título mais longo encontrado.",
        "Ordena um []Task por Titulo usando sort.Slice.",
        "Ordena o mesmo slice por Concluida, deixando as tarefas pendentes primeiro.",
        "Cria um map[int]Task a partir do slice de tarefas, usando o campo ID como chave.",
        "Implementa BuscarPorID(id int, m map[int]Task) (Task, bool), seguindo o padrão idiomático de devolver o valor e um booleano ok.",
        "Implementa RemoverPorID(id int, m map[int]Task), que remove a entrada correspondente usando delete().",
        "Escreve um exemplo lado a lado que mostra a diferença entre um array [5]int, de tamanho fixo, e um slice []int, de tamanho dinâmico.",
        "Cria um map[string]int que conta a frequência de cada palavra numa frase, usando strings.Fields combinado com um loop.",
        "Cria uma matriz 3x3 como slice de slices ([][]int) e imprime-a de forma formatada.",
        "Implementa Copiar(tarefas []Task) []Task usando copy(), e prova que alterar a cópia não afeta o slice original.",
        "Implementa Achatar(matriz [][]int) []int, que junta uma matriz num único slice plano.",
      ],
    },
    {
      id: "b3",
      titulo: "Bloco 3 — Error Handling idiomático",
      faixa: "Ex 26–35",
      descricao: "Go não tem exceptions: erros são valores normais, devolvidos como último retorno e verificados com if err != nil.",
      recursos: [
        { label: "Tour of Go — Errors", url: "https://go.dev/tour/methods/19" },
        { label: "Go by Example — Errors", url: "https://gobyexample.com/errors" },
        { label: "Go by Example — Custom Errors", url: "https://gobyexample.com/custom-errors" },
        { label: "Working with Errors in Go 1.13", url: "https://go.dev/blog/go1.13-errors" },
      ],
      exercicios: [
        "Implementa Dividir(a, b float64) (float64, error), que devolve um erro criado com errors.New quando b é igual a 0.",
        "Reescreve o método Vender() do Produto para usar errors.New em vez de devolver uma string simples.",
        "Cria o erro customizado ErroStockInsuficiente, com os campos Pedido e Disponivel int, que implementa o método Error() string.",
        "Faz Vender() devolver ErroStockInsuficiente quando for o caso, e usa errors.As no main para identificar esse tipo de erro.",
        "Faz BuscarPorID devolver (Task, error) em vez de (Task, bool), e reflete sobre quando cada abordagem faz mais sentido.",
        "Escreve uma função que executa 3 operações em sequência, em que qualquer uma pode falhar, usando o padrão early return: if err != nil { return err } depois de cada passo.",
        "Usa fmt.Errorf(\"contexto: %w\", err) para adicionares contexto a um erro sem perderes o erro original.",
        "Cria o sentinel error var ErrNaoEncontrado = errors.New(\"não encontrado\"), usa-o em BuscarPorID e verifica-o com errors.Is.",
        "Implementa ValidarTask(t Task) error, que devolve um erro descritivo quando o campo Titulo está vazio.",
        "Usa defer e recover numa função que causa um panic de propósito, e recupera dele sem que o programa termine abruptamente.",
      ],
    },
    {
      id: "b4",
      titulo: "Bloco 4 — Interfaces",
      faixa: "Ex 36–45",
      descricao: "Interfaces definem comportamento, não estrutura. Qualquer tipo que implemente os métodos satisfaz a interface automaticamente.",
      recursos: [
        { label: "Tour of Go — Interfaces", url: "https://go.dev/tour/methods/9" },
        { label: "Go by Example — Interfaces", url: "https://gobyexample.com/interfaces" },
        { label: "Effective Go — Interfaces", url: "https://go.dev/doc/effective_go#interfaces" },
      ],
      exercicios: [
        "Cria a interface Concluivel com o método Concluir(), e confirma que *Task já a satisfaz sem precisares de declarar nada extra.",
        "Implementa ConcluirTudo(itens []Concluivel), uma função que recebe qualquer valor que seja \"concluível\".",
        "Cria um segundo tipo, Habito, que também implementa Concluir(), e passa uma lista mista []Concluivel com Tasks e Habitos.",
        "Cria a interface Formatavel com o método Resumo() string, e implementa ImprimirTodos(itens []Formatavel).",
        "Usa a interface vazia any na função Descrever(v any), que imprime o tipo e o valor recebidos com fmt.Printf(\"%T: %v\", v, v).",
        "Dentro de Descrever, usa uma type assertion no formato if t, ok := v.(Task); ok { ... } para identificar quando o valor é uma Task.",
        "Substitui a assertion anterior por um type switch: switch x := v.(type) { case Task: ...; case Produto: ...; default: ... }.",
        "Desenha, só a estrutura por agora, a interface Repositorio com os métodos Adicionar(Task) e BuscarPorID(int) (Task, error).",
        "Implementa a interface sort.Interface, com os métodos Len(), Less() e Swap(), num []Task customizado, e ordena-o com sort.Sort().",
        "Escreve num comentário as tuas conclusões sobre quando compensa criar uma interface em vez de usar a struct diretamente.",
      ],
    },
    {
      id: "b5",
      titulo: "Bloco 5 — Organização em pacotes",
      faixa: "Ex 46–50",
      descricao: "À medida que um projeto cresce, um único ficheiro deixa de chegar. Este bloco ensina a estrutura de pastas padrão usada pela comunidade Go.",
      recursos: [
        { label: "How to Write Go Code", url: "https://go.dev/doc/code" },
        { label: "Standard Go Project Layout", url: "https://github.com/golang-standards/project-layout" },
      ],
      exercicios: [
        "Divide um projeto que estava num único main.go em dois ficheiros, main.go e task.go, mantendo ambos no mesmo pacote main.",
        "Cria um pacote separado numa pasta models/, com o ficheiro task.go dentro dela declarado como package models, e importa-o em main.go.",
        "Move o struct Produto também para dentro de models/.",
        "Cria uma pasta services/ com uma função que recebe []models.Task e devolve estatísticas, como a percentagem de tarefas concluídas.",
        "Confirma que o comando go build ./... corre sem erros com esta nova estrutura de pastas.",
      ],
    },
    {
      id: "b6",
      titulo: "Bloco 6 — Ferramentas: lint, testes e CI",
      faixa: "Ex 51–60",
      descricao: "Escrever código é metade do trabalho. A outra metade é usar ferramentas que apanham erros antes de chegarem a produção.",
      recursos: [
        { label: "golangci-lint — documentação", url: "https://golangci-lint.run/" },
        { label: "Go — pacote testing", url: "https://pkg.go.dev/testing" },
        { label: "Go by Example — Testing", url: "https://gobyexample.com/testing" },
        { label: "testify — GitHub", url: "https://github.com/stretchr/testify" },
        { label: "GitHub Actions — Go", url: "https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go" },
      ],
      exercicios: [
        "Corre go vet ./... em todo o projeto e corrige os avisos que aparecerem.",
        "Instala o golangci-lint e corre golangci-lint run.",
        "Escreve TestResumo, um table-driven test para o método Resumo().",
        "Escreve TestVender, que testa o caso de sucesso e o caso em que ocorre ErroStockInsuficiente.",
        "Escreve TestBuscarPorID, testando tanto o caso em que o item é encontrado como o caso em que não é.",
        "Escreve TestValidarTask, testando um título vazio e um título válido.",
        "Instala o testify e reescreve um dos testes anteriores usando assert.Equal.",
        "Cria o ficheiro .github/workflows/go.yml para correr go build e go test automaticamente a cada push.",
        "Corre a suite de testes toda com go test -v ./... a partir da raiz do projeto.",
        "Compara correr os testes manualmente com deixar o CI correr sozinho a cada push, e repara na diferença que isso faz na tua confiança para alterar código.",
      ],
    },
    {
      id: "b7",
      titulo: "Bloco 7 — JSON (encoding/decoding)",
      faixa: "Ex 61–68",
      descricao: "Uma API precisa de converter dados Go para JSON e vice-versa. É assim que ela comunica com o mundo exterior.",
      recursos: [
        { label: "Go by Example — JSON", url: "https://gobyexample.com/json" },
        { label: "pacote encoding/json", url: "https://pkg.go.dev/encoding/json" },
        { label: "JSON and Go — blog oficial", url: "https://go.dev/blog/json" },
      ],
      exercicios: [
        "Adiciona tags JSON ao struct Task: json:\"id\", json:\"titulo\" e json:\"concluida\".",
        "Usa json.Marshal(task) para converter um Task em []byte no formato JSON, e imprime o resultado como string.",
        "Usa json.Unmarshal para fazer o caminho inverso, convertendo uma string JSON de volta para um Task.",
        "Usa json.MarshalIndent para obteres o mesmo resultado, mas formatado e mais fácil de ler.",
        "Faz o marshal de um []Task inteiro e confirma que o resultado sai como um array JSON.",
        "Usa a tag json:\"desconto,omitempty\" para omitires um campo do JSON quando ele estiver vazio.",
        "Lê um ficheiro JSON com os.ReadFile e converte o conteúdo, com Unmarshal, para um slice de Tasks.",
        "Escreve um slice de Tasks para um ficheiro JSON, combinando json.Marshal com os.WriteFile.",
      ],
    },
    {
      id: "b8",
      titulo: "Bloco 8 — net/http básico",
      faixa: "Ex 69–78",
      descricao: "O pacote net/http da standard library já permite construir um servidor web completo, sem bibliotecas externas.",
      recursos: [
        { label: "Go by Example — HTTP Servers", url: "https://gobyexample.com/http-servers" },
        { label: "Go by Example — HTTP Clients", url: "https://gobyexample.com/http-clients" },
        { label: "pacote net/http", url: "https://pkg.go.dev/net/http" },
        { label: "Go Web Examples", url: "https://gowebexamples.com/" },
      ],
      exercicios: [
        "Cria um servidor HTTP mínimo com http.HandleFunc(\"/\", handler) e http.ListenAndServe(\":8080\", nil).",
        "Cria um handler que responde \"pong\" quando a rota /ping é chamada.",
        "Cria um handler que lê um query param, de forma que /saudacao?nome=Clesio responda \"Olá, Clesio\".",
        "Cria um handler que responde em JSON, definindo o Content-Type correto e usando json.NewEncoder(w).Encode(tarefas).",
        "Usa http.Error(w, \"mensagem\", http.StatusNotFound) para devolveres um erro HTTP com o código correto.",
        "Lê o método do pedido através de r.Method e responde de forma diferente consoante seja GET ou POST.",
        "Lê o corpo de um pedido POST com json.NewDecoder(r.Body).Decode(&task).",
        "Cria um middleware simples que envolve um handler e imprime, com time.Since, quanto tempo a resposta demorou.",
        "Testa os teus endpoints com curl ou com uma ferramenta como Postman ou Insomnia.",
        "O objetivo deste bloco é perceberes net/http puro antes de passares a usar um router.",
      ],
    },
    {
      id: "b9",
      titulo: "Bloco 9 — Router chi + estrutura de API",
      faixa: "Ex 79–85",
      descricao: "net/http sozinho fica limitado à medida que a API cresce; chi é um router leve que resolve isso sem ficar pesado.",
      recursos: [
        { label: "chi — documentação oficial", url: "https://github.com/go-chi/chi" },
        { label: "chi — exemplos oficiais", url: "https://github.com/go-chi/chi/tree/master/_examples" },
      ],
      exercicios: [
        "Instala o chi e substitui http.HandleFunc por r := chi.NewRouter().",
        "Cria uma rota com parâmetro, usando r.Get(\"/tasks/{id}\", handler) e lendo o valor com chi.URLParam(r, \"id\").",
        "Agrupa rotas relacionadas com r.Route(\"/tasks\", func(r chi.Router) { ... }).",
        "Usa um middleware do próprio chi, como r.Use(middleware.Logger).",
        "Organiza os handlers num ficheiro próprio, handlers/task_handler.go.",
        "Separa o projeto em três camadas: handler, que recebe o pedido HTTP; service, com a regra de negócio; e repository, que por agora guarda os dados em memória com um map.",
        "Explica por escrito por que razão separaste o projeto em camadas.",
      ],
    },
    {
      id: "b10",
      titulo: "Bloco 10 — CRUD completo em memória",
      faixa: "Ex 86–92",
      descricao: "Junta tudo: uma API real de gestão de tarefas, com as quatro operações fundamentais.",
      recursos: [
        { label: "Reaproveita recursos dos Blocos 7, 8 e 9", url: "" },
      ],
      exercicios: [
        "Implementa POST /tasks, que cria uma nova Task e gera o ID automaticamente através de um contador incremental.",
        "Implementa GET /tasks, que lista todas as tarefas existentes.",
        "Implementa GET /tasks/{id}, que devolve uma tarefa específica, ou 404 quando ela não existir.",
        "Implementa PUT /tasks/{id}, que atualiza o título e/ou o estado de uma tarefa.",
        "Implementa DELETE /tasks/{id}, que remove uma tarefa.",
        "Implementa PATCH /tasks/{id}/concluir, um endpoint dedicado que só marca a tarefa como concluída.",
        "Adiciona validação, de forma que um POST com o título vazio devolva 400 Bad Request com uma mensagem clara.",
      ],
    },
    {
      id: "b11",
      titulo: "Bloco 11 — Testes das regras de negócio",
      faixa: "Ex 93–97",
      descricao: "Testar a lógica de negócio isoladamente torna os testes rápidos e fáceis de correr centenas de vezes por dia.",
      recursos: [
        { label: "Reaproveita recursos do Bloco 6", url: "" },
      ],
      exercicios: [
        "Escreve TestCriarTask, testando diretamente a função do service, sem passar pelo handler HTTP.",
        "Escreve TestConcluirTask, seguindo a mesma ideia para a operação de concluir uma tarefa.",
        "Escreve TestListarTarefasPendentes, reaproveitando a lógica de filtro que já criaste no Bloco 2.",
        "Testa o repository isoladamente, confirmando que Adicionar e BuscarPorID funcionam corretamente em conjunto.",
        "Corre go test -v ./... em todo o projeto e confirma que todos os testes passam.",
      ],
    },
    {
      id: "b12",
      titulo: "Bloco 12 — Projeto final: deploy da API",
      faixa: "Ex 98–100",
      descricao: "Junta tudo numa API CRUD completa, publicada e testável a partir de fora da tua máquina.",
      recursos: [
        { label: "Render — Deploy a Go app", url: "https://render.com/docs/deploy-go-nethttp" },
        { label: "Railway — documentação", url: "https://docs.railway.app/" },
        { label: "Writing a README", url: "https://www.makeareadme.com/" },
      ],
      exercicios: [
        "Junta tudo numa API CRUD completa: arquitetura em camadas, JSON, validação de erros e os testes das regras de negócio.",
        "Escreve um README curto que explique cada endpoint: método, rota, e um exemplo de request e de response.",
        "Faz o deploy da API no Render ou no Railway, e testa-a a partir de fora da tua máquina usando curl.",
      ],
    },
  ],
};

const TRILHA_DOMINIOS = {
  id: "dominios",
  titulo: "Domínios práticos",
  intro: "4 domínios práticos para consolidares composição e interfaces em Go, trocando herança e classes abstratas por um struct base embutido e comportamento definido através de interfaces. Encaixa depois do Bloco 4 e antes ou durante o Bloco 10.",
  blocos: [
    {
      id: "d1",
      titulo: "Domínio 1 — LAM: Gestão de Passagens de Voo",
      faixa: "12 exercícios",
      descricao: "Sistema de gestão de passagens de voo com dois tipos de passagem: internacional (direta ou em trânsito) e doméstica. Modela-se com um struct base embutido e uma interface para o comportamento que varia entre os tipos.",
      recursos: [],
      encaixaDepoisDe: "b4",
      reaproveitaEm: ["b7", "b9", "b10"],
      exercicios: [
        "Cria o struct base Passagem, com os campos CodigoVoo, Nome, Apelido, DataPartida, HoraPartida, HoraChegada, Estado, Origem e Destino, todos string, e ValorBase float64.",
        "Cria a interface CalculadoraValor, com o método ValorFinal() float64.",
        "Cria o struct PassagemInternacional, que embute Passagem e adiciona os campos TemVisto, Directo e RefeicaoExtra bool, e HorasTransito int. Implementa ValorFinal() seguindo estas regras: uma passagem direta com refeição extra soma 3000 ao valor; uma passagem em trânsito entre 6 e 12 horas tem desconto de 10%; uma passagem em trânsito acima de 12 horas dá direito a hotel; a ausência de visto acrescenta uma taxa de 25%; e todas as passagens incluem 16% de IVA.",
        "Cria o struct PassagemDomestica, que embute Passagem e adiciona o campo Periodo string. Implementa ValorFinal(): o período da tarde paga mais 10%, o da noite paga mais 20%, e todas incluem 16% de IVA.",
        "Implementa LerPassagensDeFicheiro(caminho string) ([]CalculadoraValor, error), que lê um ficheiro com pelo menos 20 linhas e devolve um slice da interface. Repara que consegues guardar os dois tipos concretos no mesmo slice: isto é polimorfismo em Go.",
        "Implementa ContarPorTipo(passagens []CalculadoraValor) (internacionais, domesticas int), usando type assertion ou type switch para distinguir os dois tipos.",
        "Implementa ValorTotalPago(passagens []CalculadoraValor) float64, que soma o ValorFinal() de todas as passagens sem precisar de saber o tipo concreto de cada uma.",
        "Implementa PassagensDoMes(passagens []CalculadoraValor, mes int) []CalculadoraValor, que filtra as passagens pelo mês da DataPartida.",
        "Implementa SituacaoEmpresa(valorTotal, orcamento float64) (lucro bool, valor float64), aplicando a regra do orçamento de 750.000,00Mts.",
        "Constrói a versão em linha de comandos: um menu no terminal com as opções ler ficheiro, listar por tipo, calcular total, cancelar por código de voo e sair.",
        "Constrói a versão em API: os endpoints GET /passagens, GET /passagens/tipo/{tipo}, GET /passagens/total e DELETE /passagens/{codigoVoo}.",
        "Como bónus, gera um relatório exportável em JSON, com json.MarshalIndent, ou em CSV, em vez de PDF.",
      ],
    },
    {
      id: "d2",
      titulo: "Domínio 2 — Movitel: Pedidos de Requisição de Celulares",
      faixa: "8 exercícios",
      descricao: "Sistema de pedidos de requisição de telemóveis, com a mesma lógica de composição do Domínio 1: um struct base Pedido e três variações que calculam o valor a pagar de forma diferente.",
      recursos: [],
      encaixaDepoisDe: "b4",
      reaproveitaEm: ["b10"],
      exercicios: [
        "Cria o struct base Pedido, com os campos Codigo int, NomeCliente string, Marca string e Valor float64.",
        "Cria a interface CalculadoraPedido, com o método ValorAPagar() float64.",
        "Cria o struct PedidoCorporativo, que embute Pedido e adiciona o campo Quantidade int. O valor final varia consoante a quantidade de telemóveis pedidos.",
        "Cria o struct PedidoIndividual, que embute Pedido e adiciona o campo TipoCompra string. Aplica um desconto de 5% quando TipoCompra é igual a \"Novo\".",
        "Cria o struct PedidoColaborador, que embute Pedido e adiciona o campo NumDeducoes int. O valor a pagar é o valor de cada dedução individual.",
        "Todos os tipos de pedido aplicam ainda 16% de IVA. Decide se essa regra fica na própria interface ou numa função auxiliar partilhada entre os três tipos.",
        "Cria um map[int]CalculadoraPedido que regista os pedidos por código, e implementa uma função BuscarPorID para os encontrar.",
        "Constrói a versão em linha de comandos ou em API: registar um pedido, listar os pedidos numa tabela, calcular o valor total com IVA incluído e cancelar um pedido pelo código.",
      ],
    },
    {
      id: "d3",
      titulo: "Domínio 3 — Tekken 8: Participantes de Campeonato",
      faixa: "6 exercícios",
      descricao: "Domínio mais simples, sem hierarquia entre structs, ideal para praticares slices e leitura de ficheiros de forma isolada.",
      recursos: [],
      encaixaDepoisDe: "b2",
      reaproveitaEm: ["b3"],
      exercicios: [
        "Cria o struct Participante, com os campos Nome string, Rounds int, TempoMedio float64 e Resultado string, que pode ser \"ganhou\" ou \"perdeu\".",
        "Implementa LerParticipantes(caminho string) ([]Participante, error), que lê os participantes a partir de um ficheiro.",
        "Implementa ContarResultados(participantes []Participante) (ganharam, perderam int).",
        "Implementa MenorTempoEntreVencedores(participantes []Participante) (Participante, error), que devolve um erro quando não existir nenhum vencedor.",
        "Implementa ValorTotalPremios(participantes []Participante) float64, atribuindo 1000Mts a quem ganhou em 2 ou 3 rounds.",
        "Como bónus, gera uma matriz [][]float64 de 5 linhas por 10 colunas com valores aleatórios de math/rand, extrai a 3ª e a 5ª linha como slices próprios, e calcula o produto total de todos os elementos.",
      ],
    },
    {
      id: "d4",
      titulo: "Domínio 4 — EDM/FIPAG: Faturação + Atlético de Moçambique",
      faixa: "8 exercícios",
      descricao: "Dois problemas independentes no mesmo domínio: faturação de energia e água, e classificação de um campeonato de futebol. Bom para praticares sem misturares as duas lógicas.",
      recursos: [],
      encaixaDepoisDe: "b2",
      reaproveitaEm: ["b6"],
      exercicios: [
        "Cria o struct Cliente, com os campos Nome string, KiloJoules int, Litros int e Tipo string, que pode ser \"E\" de empresa ou \"P\" de particular.",
        "Implementa ValorAPagar(c Cliente) float64: a EDM cobra 2Mt por KiloJoule e a FIPAG cobra 3Mt por Litro, com desconto de 10% quando o consumo passa de 100, e 16% de IVA aplicado depois do desconto.",
        "Implementa ContarPorTipo(clientes []Cliente) (empresas, particulares int).",
        "Implementa ValorTotalPorFornecedor(clientes []Cliente) (totalEDM, totalFIPAG float64).",
        "Implementa FornecedorQueMaisFaturou(totalEDM, totalFIPAG float64) string.",
        "Problema independente sobre o Atlético de Moçambique: cria os slices golosMarcados, golosSofridos e diferenca, todos []int, para 10 jogos.",
        "Implementa CalcularPontuacao(diferenca []int) int: uma diferença negativa vale 0 pontos, zero vale 1 ponto, e uma diferença positiva vale 3 pontos.",
        "Implementa o teu próprio BubbleSort, escrito manualmente sobre diferenca, sem usares sort.Slice. É treino de lógica antes de dependeres da standard library.",
      ],
    },
  ],
};

const TRILHAS = [TRILHA_PRINCIPAL, TRILHA_DOMINIOS];
